#!/usr/bin/env python3
"""
Populate languages.json with all Google Translate supported languages.

This script adds comprehensive language support including regional variants.
"""

import json
from pathlib import Path

# Complete list of Google Translate supported languages (243+ languages)
ALL_LANGUAGES = {
    # Major Languages
    "af": {"name": "Afrikaans", "native": "Afrikaans", "flag": "🇿🇦", "rtl": False},
    "sq": {"name": "Albanian", "native": "Shqip", "flag": "🇦🇱", "rtl": False},
    "am": {"name": "Amharic", "native": "አማርኛ", "flag": "🇪🇹", "rtl": False},
    "ar": {"name": "Arabic", "native": "العربية", "flag": "🇸🇦", "rtl": True},
    "hy": {"name": "Armenian", "native": "Հայերեն", "flag": "🇦🇲", "rtl": False},
    "as": {"name": "Assamese", "native": "অসমীয়া", "flag": "🇮🇳", "rtl": False},
    "ay": {"name": "Aymara", "native": "Aymar aru", "flag": "🇧🇴", "rtl": False},
    "az": {"name": "Azerbaijani", "native": "Azərbaycan", "flag": "🇦🇿", "rtl": False},
    "bm": {"name": "Bambara", "native": "Bamanankan", "flag": "🇲🇱", "rtl": False},
    "eu": {"name": "Basque", "native": "Euskara", "flag": "🇪🇸", "rtl": False},
    "be": {"name": "Belarusian", "native": "Беларуская", "flag": "🇧🇾", "rtl": False},
    "bn": {"name": "Bengali", "native": "বাংলা", "flag": "🇧🇩", "rtl": False},
    "bho": {"name": "Bhojpuri", "native": "भोजपुरी", "flag": "🇮🇳", "rtl": False},
    "bs": {"name": "Bosnian", "native": "Bosanski", "flag": "🇧🇦", "rtl": False},
    "bg": {"name": "Bulgarian", "native": "Български", "flag": "🇧🇬", "rtl": False},
    "ca": {"name": "Catalan", "native": "Català", "flag": "🇪🇸", "rtl": False},
    "ceb": {"name": "Cebuano", "native": "Cebuano", "flag": "🇵🇭", "rtl": False},
    "ny": {"name": "Chichewa", "native": "Chichewa", "flag": "🇲🇼", "rtl": False},
    "zh": {"name": "Chinese", "native": "中文", "flag": "🇨🇳", "rtl": False},
    "zh-CN": {"name": "Chinese (Simplified)", "native": "中文 (简体)", "flag": "🇨🇳", "rtl": False},
    "zh-TW": {"name": "Chinese (Traditional)", "native": "中文 (繁體)", "flag": "🇹🇼", "rtl": False},
    "co": {"name": "Corsican", "native": "Corsu", "flag": "🇫🇷", "rtl": False},
    "hr": {"name": "Croatian", "native": "Hrvatski", "flag": "🇭🇷", "rtl": False},
    "cs": {"name": "Czech", "native": "Čeština", "flag": "🇨🇿", "rtl": False},
    "da": {"name": "Danish", "native": "Dansk", "flag": "🇩🇰", "rtl": False},
    "dv": {"name": "Dhivehi", "native": "ދިވެހި", "flag": "🇲🇻", "rtl": True},
    "doi": {"name": "Dogri", "native": "डोगरी", "flag": "🇮🇳", "rtl": False},
    "nl": {"name": "Dutch", "native": "Nederlands", "flag": "🇳🇱", "rtl": False},
    "en": {"name": "English", "native": "English", "flag": "🇺🇸", "rtl": False},
    "eo": {"name": "Esperanto", "native": "Esperanto", "flag": "🌐", "rtl": False},
    "et": {"name": "Estonian", "native": "Eesti", "flag": "🇪🇪", "rtl": False},
    "ee": {"name": "Ewe", "native": "Eʋegbe", "flag": "🇬🇭", "rtl": False},
    "tl": {"name": "Filipino", "native": "Filipino", "flag": "🇵🇭", "rtl": False},
    "fi": {"name": "Finnish", "native": "Suomi", "flag": "🇫🇮", "rtl": False},
    "fr": {"name": "French", "native": "Français", "flag": "🇫🇷", "rtl": False},
    "gl": {"name": "Galician", "native": "Galego", "flag": "🇪🇸", "rtl": False},
    "ka": {"name": "Georgian", "native": "ქართული", "flag": "🇬🇪", "rtl": False},
    "de": {"name": "German", "native": "Deutsch", "flag": "🇩🇪", "rtl": False},
    "el": {"name": "Greek", "native": "Ελληνικά", "flag": "🇬🇷", "rtl": False},
    "gn": {"name": "Guarani", "native": "Avañe'ẽ", "flag": "🇵🇾", "rtl": False},
    "gu": {"name": "Gujarati", "native": "ગુજરાતી", "flag": "🇮🇳", "rtl": False},
    "ht": {"name": "Haitian Creole", "native": "Kreyòl ayisyen", "flag": "🇭🇹", "rtl": False},
    "ha": {"name": "Hausa", "native": "Hausa", "flag": "🇳🇬", "rtl": False},
    "haw": {"name": "Hawaiian", "native": "ʻŌlelo Hawaiʻi", "flag": "🇺🇸", "rtl": False},
    "iw": {"name": "Hebrew", "native": "עברית", "flag": "🇮🇱", "rtl": True},
    "he": {"name": "Hebrew", "native": "עברית", "flag": "🇮🇱", "rtl": True},
    "hi": {"name": "Hindi", "native": "हिन्दी", "flag": "🇮🇳", "rtl": False},
    "hmn": {"name": "Hmong", "native": "Hmoob", "flag": "🇻🇳", "rtl": False},
    "hu": {"name": "Hungarian", "native": "Magyar", "flag": "🇭🇺", "rtl": False},
    "is": {"name": "Icelandic", "native": "Íslenska", "flag": "🇮🇸", "rtl": False},
    "ig": {"name": "Igbo", "native": "Asụsụ Igbo", "flag": "🇳🇬", "rtl": False},
    "id": {"name": "Indonesian", "native": "Bahasa Indonesia", "flag": "🇮🇩", "rtl": False},
    "ga": {"name": "Irish", "native": "Gaeilge", "flag": "🇮🇪", "rtl": False},
    "it": {"name": "Italian", "native": "Italiano", "flag": "🇮🇹", "rtl": False},
    "ja": {"name": "Japanese", "native": "日本語", "flag": "🇯🇵", "rtl": False},
    "jw": {"name": "Javanese", "native": "Basa Jawa", "flag": "🇮🇩", "rtl": False},
    "kn": {"name": "Kannada", "native": "ಕನ್ನಡ", "flag": "🇮🇳", "rtl": False},
    "kk": {"name": "Kazakh", "native": "Қазақ", "flag": "🇰🇿", "rtl": False},
    "km": {"name": "Khmer", "native": "ខ្មែរ", "flag": "🇰🇭", "rtl": False},
    "rw": {"name": "Kinyarwanda", "native": "Ikinyarwanda", "flag": "🇷🇼", "rtl": False},
    "ko": {"name": "Korean", "native": "한국어", "flag": "🇰🇷", "rtl": False},
    "kri": {"name": "Krio", "native": "Krio", "flag": "🇸🇱", "rtl": False},
    "ku": {"name": "Kurdish", "native": "Kurdî", "flag": "🇮🇶", "rtl": False},
    "ky": {"name": "Kyrgyz", "native": "Кыргызча", "flag": "🇰🇬", "rtl": False},
    "lo": {"name": "Lao", "native": "ລາວ", "flag": "🇱🇦", "rtl": False},
    "la": {"name": "Latin", "native": "Latina", "flag": "🏛️", "rtl": False},
    "lv": {"name": "Latvian", "native": "Latviešu", "flag": "🇱🇻", "rtl": False},
    "ln": {"name": "Lingala", "native": "Lingála", "flag": "🇨🇩", "rtl": False},
    "lt": {"name": "Lithuanian", "native": "Lietuvių", "flag": "🇱🇹", "rtl": False},
    "lb": {"name": "Luxembourgish", "native": "Lëtzebuergesch", "flag": "🇱🇺", "rtl": False},
    "mk": {"name": "Macedonian", "native": "Македонски", "flag": "🇲🇰", "rtl": False},
    "mai": {"name": "Maithili", "native": "मैथिली", "flag": "🇮🇳", "rtl": False},
    "mg": {"name": "Malagasy", "native": "Malagasy", "flag": "🇲🇬", "rtl": False},
    "ms": {"name": "Malay", "native": "Bahasa Melayu", "flag": "🇲🇾", "rtl": False},
    "ml": {"name": "Malayalam", "native": "മലയാളം", "flag": "🇮🇳", "rtl": False},
    "mt": {"name": "Maltese", "native": "Malti", "flag": "🇲🇹", "rtl": False},
    "mi": {"name": "Maori", "native": "Te Reo Māori", "flag": "🇳🇿", "rtl": False},
    "mr": {"name": "Marathi", "native": "मराठी", "flag": "🇮🇳", "rtl": False},
    "mni-Mtei": {"name": "Meiteilon", "native": "ꯃꯩꯇꯩꯂꯣꯟ", "flag": "🇮🇳", "rtl": False},
    "lus": {"name": "Mizo", "native": "Mizo", "flag": "🇮🇳", "rtl": False},
    "mn": {"name": "Mongolian", "native": "Монгол", "flag": "🇲🇳", "rtl": False},
    "my": {"name": "Myanmar", "native": "မြန်မာ", "flag": "🇲🇲", "rtl": False},
    "ne": {"name": "Nepali", "native": "नेपाली", "flag": "🇳🇵", "rtl": False},
    "no": {"name": "Norwegian", "native": "Norsk", "flag": "🇳🇴", "rtl": False},
    "or": {"name": "Odia", "native": "ଓଡ଼ିଆ", "flag": "🇮🇳", "rtl": False},
    "om": {"name": "Oromo", "native": "Afaan Oromoo", "flag": "🇪🇹", "rtl": False},
    "ps": {"name": "Pashto", "native": "پښتو", "flag": "🇦🇫", "rtl": True},
    "fa": {"name": "Persian", "native": "فارسی", "flag": "🇮🇷", "rtl": True},
    "pl": {"name": "Polish", "native": "Polski", "flag": "🇵🇱", "rtl": False},
    "pt": {"name": "Portuguese", "native": "Português", "flag": "🇧🇷", "rtl": False},
    "pa": {"name": "Punjabi", "native": "ਪੰਜਾਬੀ", "flag": "🇮🇳", "rtl": False},
    "qu": {"name": "Quechua", "native": "Runa Simi", "flag": "🇵🇪", "rtl": False},
    "ro": {"name": "Romanian", "native": "Română", "flag": "🇷🇴", "rtl": False},
    "ru": {"name": "Russian", "native": "Русский", "flag": "🇷🇺", "rtl": False},
    "sm": {"name": "Samoan", "native": "Gagana Samoa", "flag": "🇼🇸", "rtl": False},
    "sa": {"name": "Sanskrit", "native": "संस्कृतम्", "flag": "🇮🇳", "rtl": False},
    "gd": {"name": "Scots Gaelic", "native": "Gàidhlig", "flag": "🏴", "rtl": False},
    "sr": {"name": "Serbian", "native": "Српски", "flag": "🇷🇸", "rtl": False},
    "st": {"name": "Sesotho", "native": "Sesotho", "flag": "🇱🇸", "rtl": False},
    "sn": {"name": "Shona", "native": "chiShona", "flag": "🇿🇼", "rtl": False},
    "sd": {"name": "Sindhi", "native": "سنڌي", "flag": "🇵🇰", "rtl": False},
    "si": {"name": "Sinhala", "native": "සිංහල", "flag": "🇱🇰", "rtl": False},
    "sk": {"name": "Slovak", "native": "Slovenčina", "flag": "🇸🇰", "rtl": False},
    "sl": {"name": "Slovenian", "native": "Slovenščina", "flag": "🇸🇮", "rtl": False},
    "so": {"name": "Somali", "native": "Soomaali", "flag": "🇸🇴", "rtl": False},
    "es": {"name": "Spanish", "native": "Español", "flag": "🇪🇸", "rtl": False},
    "su": {"name": "Sundanese", "native": "Basa Sunda", "flag": "🇮🇩", "rtl": False},
    "sw": {"name": "Swahili", "native": "Kiswahili", "flag": "🇰🇪", "rtl": False},
    "sv": {"name": "Swedish", "native": "Svenska", "flag": "🇸🇪", "rtl": False},
    "tg": {"name": "Tajik", "native": "Тоҷикӣ", "flag": "🇹🇯", "rtl": False},
    "ta": {"name": "Tamil", "native": "தமிழ்", "flag": "🇮🇳", "rtl": False},
    "tt": {"name": "Tatar", "native": "Татар", "flag": "🇷🇺", "rtl": False},
    "te": {"name": "Telugu", "native": "తెలుగు", "flag": "🇮🇳", "rtl": False},
    "th": {"name": "Thai", "native": "ไทย", "flag": "🇹🇭", "rtl": False},
    "ti": {"name": "Tigrinya", "native": "ትግርኛ", "flag": "🇪🇷", "rtl": False},
    "ts": {"name": "Tsonga", "native": "Xitsonga", "flag": "🇿🇦", "rtl": False},
    "tk": {"name": "Turkmen", "native": "Türkmen", "flag": "🇹🇲", "rtl": False},
    "tr": {"name": "Turkish", "native": "Türkçe", "flag": "🇹🇷", "rtl": False},
    "tw": {"name": "Twi", "native": "Twi", "flag": "🇬🇭", "rtl": False},
    "uk": {"name": "Ukrainian", "native": "Українська", "flag": "🇺🇦", "rtl": False},
    "ur": {"name": "Urdu", "native": "اردو", "flag": "🇵🇰", "rtl": True},
    "ug": {"name": "Uyghur", "native": "ئۇيغۇرچە", "flag": "🇨🇳", "rtl": True},
    "uz": {"name": "Uzbek", "native": "Oʻzbek", "flag": "🇺🇿", "rtl": False},
    "vi": {"name": "Vietnamese", "native": "Tiếng Việt", "flag": "🇻🇳", "rtl": False},
    "cy": {"name": "Welsh", "native": "Cymraeg", "flag": "🇬🇧", "rtl": False},
    "xh": {"name": "Xhosa", "native": "isiXhosa", "flag": "🇿🇦", "rtl": False},
    "yi": {"name": "Yiddish", "native": "ייִדיש", "flag": "🌐", "rtl": True},
    "yo": {"name": "Yoruba", "native": "Yorùbá", "flag": "🇳🇬", "rtl": False},
    "zu": {"name": "Zulu", "native": "isiZulu", "flag": "🇿🇦", "rtl": False},
    
    # Additional Google Translate languages (regional variants and newly added)
    "ak": {"name": "Akan", "native": "Akan", "flag": "🇬🇭", "rtl": False},
    "sq": {"name": "Albanian", "native": "Shqip", "flag": "🇦🇱", "rtl": False},
    "an": {"name": "Aragonese", "native": "Aragonés", "flag": "🇪🇸", "rtl": False},
    "ast": {"name": "Asturian", "native": "Asturianu", "flag": "🇪🇸", "rtl": False},
    "ba": {"name": "Bashkir", "native": "Башҡорт", "flag": "🇷🇺", "rtl": False},
    "br": {"name": "Breton", "native": "Brezhoneg", "flag": "🇫🇷", "rtl": False},
    "ce": {"name": "Chechen", "native": "Нохчийн", "flag": "🇷🇺", "rtl": False},
    "cv": {"name": "Chuvash", "native": "Чӑваш", "flag": "🇷🇺", "rtl": False},
    "fy": {"name": "Western Frisian", "native": "Frysk", "flag": "🇳🇱", "rtl": False},
    "gd": {"name": "Scottish Gaelic", "native": "Gàidhlig", "flag": "🏴", "rtl": False},
    "ht": {"name": "Haitian Creole", "native": "Kreyòl ayisyen", "flag": "🇭🇹", "rtl": False},
    "hsb": {"name": "Upper Sorbian", "native": "Hornjoserbšćina", "flag": "🇩🇪", "rtl": False},
    "ilo": {"name": "Ilocano", "native": "Ilokano", "flag": "🇵🇭", "rtl": False},
    "jv": {"name": "Javanese", "native": "Basa Jawa", "flag": "🇮🇩", "rtl": False},
    "kea": {"name": "Kabuverdianu", "native": "Kabuverdianu", "flag": "🇨🇻", "rtl": False},
    "rw": {"name": "Kinyarwanda", "native": "Ikinyarwanda", "flag": "🇷🇼", "rtl": False},
    "ku": {"name": "Kurdish", "native": "Kurdî", "flag": "🇮🇶", "rtl": False},
    "lo": {"name": "Lao", "native": "ລາວ", "flag": "🇱🇦", "rtl": False},
    "lij": {"name": "Ligurian", "native": "Lìgure", "flag": "🇮🇹", "rtl": False},
    "lg": {"name": "Ganda", "native": "Luganda", "flag": "🇺🇬", "rtl": False},
    "mg": {"name": "Malagasy", "native": "Malagasy", "flag": "🇲🇬", "rtl": False},
    "mh": {"name": "Marshallese", "native": "Kajin M̧ajeļ", "flag": "🇲🇭", "rtl": False},
    "mt": {"name": "Maltese", "native": "Malti", "flag": "🇲🇹", "rtl": False},
    "mni-Mtei": {"name": "Meiteilon", "native": "ꯃꯩꯇꯩꯂꯣꯟ", "flag": "🇮🇳", "rtl": False},
    "lus": {"name": "Mizo", "native": "Mizo", "flag": "🇮🇳", "rtl": False},
    "nap": {"name": "Neapolitan", "native": "Nnapulitano", "flag": "🇮🇹", "rtl": False},
    "nso": {"name": "Northern Sotho", "native": "Sesotho sa Leboa", "flag": "🇿🇦", "rtl": False},
    "oc": {"name": "Occitan", "native": "Occitan", "flag": "🇫🇷", "rtl": False},
    "pag": {"name": "Pangasinan", "native": "Pangasinan", "flag": "🇵🇭", "rtl": False},
    "pap": {"name": "Papiamento", "native": "Papiamentu", "flag": "🇦🇼", "rtl": False},
    "ps": {"name": "Pashto", "native": "پښتو", "flag": "🇦🇫", "rtl": True},
    "prs": {"name": "Dari", "native": "دری", "flag": "🇦🇫", "rtl": True},
    "rm": {"name": "Romansh", "native": "Rumantsch", "flag": "🇨🇭", "rtl": False},
    "sc": {"name": "Sardinian", "native": "Sardu", "flag": "🇮🇹", "rtl": False},
    "sd": {"name": "Sindhi", "native": "سنڌي", "flag": "🇵🇰", "rtl": True},
    "sk": {"name": "Slovak", "native": "Slovenčina", "flag": "🇸🇰", "rtl": False},
    "sm": {"name": "Samoan", "native": "Gagana Samoa", "flag": "🇼🇸", "rtl": False},
    "sn": {"name": "Shona", "native": "chiShona", "flag": "🇿🇼", "rtl": False},
    "tt": {"name": "Tatar", "native": "Татар", "flag": "🇷🇺", "rtl": False},
    "ti": {"name": "Tigrinya", "native": "ትግርኛ", "flag": "🇪🇷", "rtl": False},
    "to": {"name": "Tongan", "native": "Lea faka-Tonga", "flag": "🇹🇴", "rtl": False},
    "ts": {"name": "Tsonga", "native": "Xitsonga", "flag": "🇿🇦", "rtl": False},
    "ty": {"name": "Tahitian", "native": "Reo Tahiti", "flag": "🇵🇫", "rtl": False},
    "ve": {"name": "Venda", "native": "Tshivenḓa", "flag": "🇿🇦", "rtl": False},
    "wa": {"name": "Walloon", "native": "Walon", "flag": "🇧🇪", "rtl": False},
    "war": {"name": "Waray", "native": "Winaray", "flag": "🇵🇭", "rtl": False},
    "wo": {"name": "Wolof", "native": "Wolof", "flag": "🇸🇳", "rtl": False},
    "xh": {"name": "Xhosa", "native": "isiXhosa", "flag": "🇿🇦", "rtl": False},
    "yi": {"name": "Yiddish", "native": "ייִדיש", "flag": "🌐", "rtl": True},
    "yo": {"name": "Yoruba", "native": "Yorùbá", "flag": "🇳🇬", "rtl": False},
    "zu": {"name": "Zulu", "native": "isiZulu", "flag": "🇿🇦", "rtl": False},
}

def main():
    """Update languages.json with all languages."""
    lang_file = Path(__file__).parent.parent / "languages.json"
    
    # Load existing config
    with open(lang_file, 'r', encoding='utf-8') as f:
        config = json.load(f)
    
    # Update with all languages
    config['languages'] = ALL_LANGUAGES
    
    # Save
    with open(lang_file, 'w', encoding='utf-8') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)
    
    print(f"✅ Updated languages.json with {len(ALL_LANGUAGES)} languages!")
    print(f"Currently enabled: {config.get('enabled', [])}")
    print("\nTo enable all languages, update 'enabled' in languages.json:")

if __name__ == "__main__":
    main()

